apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "bgg-helm.fullname" . }}
  labels: 
{{ include "bgg-helm.labels" . | indent 4 }}
  namespace :  {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bgg-helm.name" . }}
      app.kubernetes.io/version: {{ .Values.image.version }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bgg-helm.name" . }}
        app.kubernetes.io/version: {{ .Values.image.version }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:          
               requests:
                  cpu : {{ .Values.resources.cpu }}
          env:
          - name: APP_PORT
            value: "{{ .Values.env.APP_PORT}}"
          - name: BGG_DB_HOST
            value: "bgg-db-svc.{{ .Release.Namespace }}.svc.cluster.local"   
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP